"""Mutants for kvt-fleet mutate.py: (file, old, new, name). Each flips one load-bearing
fail-closed decision; the offline test gate must go red for every one."""
F, V, H, W, B, BD = ("hook_repro/fetch.py", "hook_repro/verify.py", "hook_repro/hashing.py",
                     "hook_repro/wasm.py", "hook_repro/bind.py", "hook_repro/build.py")
CL, RM, CLI = "hook_repro/cargo_lock.py", "hook_repro/rshooks_meta.py", "hook_repro/cli.py"
HC = "hook_repro/hookc.py"
MUTANTS = [
    (F, 'if len(codes) != 1:', 'if len(codes) > 2:', "fetch: accept operator disagreement"),
    (F, 'if got != hookhash:', 'if False:', "fetch: skip SHA512Half == HookHash check"),
    (F, 'if len(nodes) < 2 and not allow_single_operator:', 'if False:', "fetch: accept single node as two operators"),
    (F, 'if le.get("validated") is not True:', 'if False:', "fetch: accept unvalidated ledger"),
    (F, '    if out["errors"]:\n        out["reason"] = "read failure: "', '    if len(out["errors"]) > 1:\n        out["reason"] = "read failure: "', "fetch: tolerate one read failure"),
    (F, 'if r["network_id"] != net["network_id"]:', 'if False:', "fetch: ignore network_id"),
    (F, 'if node.get("LedgerEntryType") != "HookDefinition":', 'if False:', "fetch: ignore entry type"),
    (F, 'if str(node.get("HookHash", "")).upper() != hookhash:', 'if False:', "fetch: ignore HookHash field"),
    (F, 'if r.get("status") != "success" or "error" in r:', 'if r.get("status") == "failure":', "fetch: accept error status"),
    (F, 'if not node_key:', 'if False:', "fetch: accept missing node key"),
    (V, 'if b1 != b2:', 'if False:', "verify: skip determinism check"),
    (V, 'if b1 != onledger:', 'if len(b1) != len(onledger):', "verify: size-only comparison"),
    (V, 'except Exception as e:  # any build failure', 'except KeyError as e:  # any build failure', "verify: build error escapes"),
    (V, 'if t1 != t2:', 'if False:', "verify: ignore source change between builds"),
    (V, 'if not f["ok"]:', 'if f["code"] is None and f["reason"] is None:', "verify: build despite failed read"),
    (V, 'rep["verdict"] = "REPRODUCED"', 'rep["verdict"] = "MISMATCH"', "verify: wrong verdict label"),
    (H, 'return hashlib.sha512(bytes(data)).digest()[:32].hex().upper()', 'return hashlib.sha512(bytes(data)).digest()[:31].hex().upper()', "hash: truncate wrong"),
    (H, 'entries.sort(key=lambda e: e[0].encode("utf-8"))', 'entries.reverse()', "tree: unsorted listing"),
    (H, '                raise TreeError("symlink in source tree: %s" % full)', '                continue', "tree: silently skip symlinks"),
    (H, 'if d in TREE_IGNORE_DIRS:', 'if d == "__pycache__":', "tree: hash .git contents"),
    (W, 'status = "same" if sa["sha256"] == sb["sha256"] else "differs"', 'status = "same"', "diff: sections always same"),
    (W, 'status = "same" if x["sha256"] == y["sha256"] else "differs"', 'status = "same"', "diff: functions always same"),
    (W, 'if len(data) < 8 or data[:4] != MAGIC:', 'if len(data) < 4:', "parse: accept bad magic"),
    (W, 'if end > len(data):', 'if False:', "parse: accept overrunning section"),
    (W, 'idx = mod["n_imported_funcs"] + k', 'idx = k', "parse: function index ignores imports"),
    (B, 'if cov != "MENTIONS_HOOKHASH":', 'if cov == "NOT_MENTIONED":', "bind: accept review naming other hashes"),
    (B, 'if rep.get("verdict") != "REPRODUCED":', 'if False:', "bind: accept non-REPRODUCED report"),
    (B, 'if (rep.get("hookhash") or "").upper() != H:', 'if False:', "bind: accept report for another hash"),
    (B, 'HEX64 = re.compile(r"(?<![0-9A-Fa-f])[0-9A-Fa-f]{64}(?![0-9A-Fa-f])")', 'HEX64 = re.compile(r"[0-9A-Fa-f]{64}")', "bind: substring of longer hex counts"),
    (B, 'if any(H.startswith(p) for p in prefixes):', 'if any(H.startswith(p) for p in prefixes) and False:', "bind: prefix-only not flagged"),
    (BD, 'if "allowed" in s and v not in s["allowed"]:', 'if False:', "build: params not allowlisted"),
    (BD, 'if "allowed_pattern" in s and not re.match(s["allowed_pattern"], v):', 'if False:', "build: pattern not enforced"),
    (BD, 'if not re.match(r"^[a-z0-9._/-]+@sha256:[0-9a-f]{64}$", r.get("base_image", "")):', 'if False:', "build: base image unpinned"),
    (BD, 'if not re.match(r"^[0-9a-f]{64}$", a.get("sha256", "")):', 'if False:', "build: artifact unpinned"),
    (BD, '    if got != a["sha256"]:', '    if False:', "build: artifact sha not checked"),
    (BD, 'if os.path.isabs(m.linkname) or not target.startswith(os.path.abspath(into) + os.sep):', 'if False:', "build: escaping symlink allowed"),
    (BD, 'h.update(json.dumps(canon, sort_keys=True, separators=(",", ":")).encode())', 'pass', "build: recipe digest ignores recipe"),
    (BD, 'if inc and not any(name == p or (p.endswith("/") and name.startswith(p)) for p in inc):', 'if inc and not any(name.startswith(p) for p in inc):', "build: exact include matches as prefix"),
    # rshooks: Cargo.lock pinning, crate unpack, sidecar, metadata.json -> recipe selection
    (CL, 'if src != CRATES_IO:', 'if False:', "lock: accept git/other-registry source"),
    (CL, 'if not SHA_RE.match(cs):', 'if False:', "lock: accept registry package without checksum"),
    (CL, 'SHA_RE = re.compile(r"^[0-9a-f]{64}$")', 'SHA_RE = re.compile(r"^[0-9a-fA-F]{63,64}$")', "lock: loose checksum format"),
    (CL, 'if not NAME_RE.match(name) or not VERSION_RE.match(ver):', 'if False:', "lock: accept unsafe name/version"),
    (CL, 'if src is None:\n            continue', 'if src is None or "git" in src:\n            continue', "lock: silently skip git sources"),
    (CL, 'if len(set((n, v) for n, v, _ in out)) != len(out):', 'if False:', "lock: accept duplicate packages"),
    (CL, 'json.dump({"files": {}, "package": sha}, f)', 'json.dump({"files": {}, "package": None}, f)', "lock: checksum json drops package sha"),
    (CL, 'h.update(("%s\\0%s\\0%s\\n" % (n, v, s)).encode())', 'h.update(("%s\\0%s\\n" % (n, v)).encode())', "lock: vendor digest ignores checksums"),
    (BD, 'if not DOCKERFILE_EXTRA_RE.match(line):', 'if False:', "build: networked image-build step allowed"),
    (BD, 'if not re.match(r"^[0-9]{1,2}g$", r.get("work_tmpfs", "1g")):', 'if False:', "build: tmpfs size unvalidated"),
    (BD, 'if not path.startswith(root + os.sep):', 'if False:', "build: LOCK may escape source tree"),
    (BD, 'if not os.path.isfile(path):', 'if False:', "build: missing LOCK accepted"),
    (BD, 'if not os.path.exists(os.path.join(pkg, "Cargo.toml")):', 'if False:', "build: crate without manifest accepted"),
    (BD, 'if claimed != sha512half(wasm):', 'if False:', "build: sidecar HookHash not checked"),
    (BD, '        raise BuildError("pipeline produced no %s" % name)', '        return None', "build: missing sidecar tolerated"),
    (BD, '    lines.extend(recipe.get("dockerfile_extra", []))', '    pass', "build: dockerfile_extra dropped"),
    (RM, 'if b.get("name") != "rshooks-build":', 'if False:', "meta: any builder name"),
    (RM, 'if not isinstance(ver, str) or not VERSION_RE.match(ver):', 'if False:', "meta: any builder version"),
    (RM, 'if type(idx) is not int or not 0 <= idx <= MAX_INDEX:', 'if not isinstance(idx, int):', "meta: index range/bool unchecked"),
    (RM, 'if not isinstance(fn, str) or not ENTRY_FN_RE.match(fn):', 'if False:', "meta: hook_fn unchecked"),
    (RM, 'if not isinstance(hh, str) or not HASH_RE.match(hh):', 'if False:', "meta: HookHash unchecked"),
    (RM, 'if not isinstance(rustc, str) or not rustc.startswith("rustc "):', 'if False:', "meta: rustc unchecked"),
    (RM, 'if not isinstance(b.get("wasm_opt"), bool):', 'if False:', "meta: wasm_opt type unchecked"),
    (RM, 'if meta["rustc"] != pin["rustc"]:', 'if not meta["rustc"].startswith("rustc 1."):', "select: toolchain version ignored"),
    (RM, 'if meta["cargo_args"] != pin["cargo_args"]:', 'if False:', "select: cargo_args ignored"),
    (RM, 'if meta["rustc_args"] != expected_rustc_args(meta["index"], pin["stack_size"]):', 'if False:', "select: rustc_args ignored"),
    (RM, 'if meta["wasm_opt"] is not pin["wasm_opt"]:', 'if False:', "select: wasm_opt ignored"),
    (RM, 'if recipe_name and recipe_name != want:', 'if False:', "select: explicit recipe overrides metadata"),
    (RM, 'if want not in buildmod.list_recipes():', 'if False:', "select: unknown version not refused early"),
    (RM, 'if not isinstance(pin, dict):', 'if False:', "select: recipe without pin block"),
    (CLI, 'if params.get("ENTRY", mp["ENTRY"]) != mp["ENTRY"]:', 'if False:', "cli: --param ENTRY overrides metadata"),
    (V, 'rep["metadata_hookhash_matches"] = metadata["hookhash"] == rep["hookhash"]', 'rep["metadata_hookhash_matches"] = True', "verify: metadata claim always matches"),
    # hookc: C hook builds, rshooks-compatible metadata, source provenance, WCE
    (HC, '    b[31 - SETHOOK_BIT // 8] ^= 1 << (SETHOOK_BIT % 8)\n    for v in values:', '    for v in values:', "hookc: SetHook bit not inverted"),
    (HC, '        b[31 - code // 8] ^= 1 << (code % 8)', '        b[code // 8] ^= 1 << (code % 8)', "hookc: mask byte order reversed"),
    (HC, '        if x not in TX_TYPES:', '        if False:', "hookc: unknown tx type accepted"),
    (HC, '        if x in seen:', '        if False:', "hookc: duplicate tx type accepted"),
    (HC, '    if unknown:', '    if False:', "hookc: unknown declaration keys ignored"),
    (HC, '    if type(idx) is not int or not 0 <= idx <= MAX_INDEX:\n        raise HookcError("index %r out of range 0..%d"', '    if not isinstance(idx, int):\n        raise HookcError("index %r out of range 0..%d"', "hookc: decl index range unchecked"),
    (HC, 'if not isinstance(name, str) or not 2 <= len(name) <= 8:', 'if not isinstance(name, str):', "hookc: HookName length unchecked (L3)"),
    (HC, '        if set(doc) - {"hook"}:', '        if False:', "hookc: toml extra tables accepted"),
    (HC, '        if mode not in ("100644", "100755"):\n            raise HookcError("source %s has %r (mode %s)', '        if False:\n            raise HookcError("source %s has %r (mode %s)', "hookc: symlink exported"),
    (HC, '    if _git(src, "status", "--porcelain", "--untracked-files=all", "--ignored=no", "--", "."):', '    if False:', "hookc: dirty work tree treated as clean"),
    (HC, '"--porcelain", "--untracked-files=all",', '"--porcelain", "--untracked-files=no",', "hookc: untracked files ignored"),
    (HC, '            if not allow_unversioned:\n                raise HookcError("no source provenance', '            if False:\n                raise HookcError("no source provenance', "hookc: unversioned source accepted"),
    (HC, '        if r["platform"] != plat:', '        if False:', "hookc: twin platform not checked"),
    (HC, '        if type(h) is not int or type(c) is not int or h < 0 or c < 0:', '        if h is None:', "hookc: WCE output unvalidated"),
    (HC, '    if rc == "1" and doc.get("valid") is False:', '    if False:', "hookc: guard rejection becomes null WCE"),
    (HC, '    if rc == "0" and doc.get("valid") is True:', '    if doc.get("valid") is True:', "hookc: WCE accepted from failed run"),
    (HC, '    if "hook" not in funcs:', '    if False:', "hookc: module without hook export"),
    (HC, '    if extra:', '    if False:', "hookc: extra exports accepted"),
    (HC, '"cbak_fn": "cbak" if "cbak" in funcs else None,', '"cbak_fn": "cbak",', "hookc: cbak_fn not detected"),
    (HC, '"HookName": decls["name"].encode().hex().upper() if', '"HookName": decls["name"].encode().hex() if', "hookc: HookName lowercase hex"),
    (HC, '("0" * 64 if decls["on_form"] == "all" else None)', '(None if decls["on_form"] == "all" else None)', "hookc: on=all dropped"),
    (HC, '    if emits and ce == []:', '    if False:', "hookc: emit with deny-all not warned"),
    (HC, '    if ce and not emits:', '    if False:', "hookc: unused can_emit not warned"),
    (HC, 'return json.dumps(meta, indent=2, ensure_ascii=False) + "\\n"', 'return json.dumps(meta, indent=2, ensure_ascii=False)', "hookc: no trailing newline"),
    (HC, '    if not isinstance(b, dict) or b.get("name") != BUILDER_NAME:', '    if not isinstance(b, dict):', "hookc: any builder name"),
    (HC, '    if b.get("version") != HOOKC_VERSION:', '    if False:', "hookc: any hookc version"),
    (HC, '    if type(idx) is not int or not 0 <= idx <= MAX_INDEX:\n        raise HookcError("index %r out of range" % idx)', '    if False:\n        raise HookcError("index %r out of range" % idx)', "hookc: meta index unchecked"),
    (HC, '    if doc.get("hook_fn") != "hook":', '    if False:', "hookc: hook_fn unchecked"),
    (HC, '    if not isinstance(hh, str) or not HASH_RE.match(hh):', '    if False:', "hookc: HookHash unchecked"),
    (HC, '        if doc.get(k) is not None and not MASK_RE.match(str(doc[k])):', '        if False:', "hookc: masks unchecked"),
    (HC, '    if not isinstance(params, dict) or not all(isinstance(v, str) for v in params.values()):', '    if not isinstance(params, dict):', "hookc: param values unchecked"),
    (HC, '    if (not isinstance(plats, dict) or set(plats) != set(toolchain(tc)["platforms"])', '    if (not isinstance(plats, dict)', "hookc: empty / partial platforms accepted"),
    (HC, '    if not isinstance(src, dict):', '    if False:', "hookc: missing source block accepted"),
    (HC, '    if not isinstance(vcs, dict) or vcs.get("type") != "git":', '    if not isinstance(vcs, dict):', "hookc: non-git vcs accepted"),
    (HC, '    if not GIT_RE.match(str(vcs.get("commit"))) or not GIT_RE.match(str(vcs.get("tree"))):', '    if False:', "hookc: commit/tree unchecked"),
    (HC, '    if vcs.get("dirty") is not False:', '    if vcs.get("dirty") is True:', "hookc: dirty missing accepted"),
    (HC, '    if not REL_RE.match(path or ""):\n        raise HookcError("bad source path', '    if False:\n        raise HookcError("bad source path', "hookc: meta/export path unchecked"),
    (HC, '    if not SHA_RE.match(str(src.get("tree_sha256"))):', '    if False:', "hookc: tree_sha256 unchecked"),
    (HC, '    if entry is not None and not ENTRY_RE.match(str(entry)):', '    if False:', "hookc: meta entry unchecked"),
    (HC, '    if pin.get("recipe") != want:', '    if False:', "hookc: twin recipe name unchecked"),
    (HC, '    if pin.get("recipe_digest") != have:', '    if False:', "hookc: toolchain drift accepted"),
    (HC, '    if plat not in plats:', '    if False:', "hookc: unlisted platform accepted"),
    (HC, '        if not ENTRY_RE.match(entry):', '        if False:', "hookc: entry name unchecked"),
    (HC, '        if not ep:', '        if False:', "hookc: entry on toolchain without selector"),
    (HC, '    if w1 != w2:', '    if False:', "hookc: nondeterministic build accepted"),
    (HC, '        if p not in tc["platforms"]:', '        if False:', "hookc: missing twin not refused"),
    (HC, '            if results[plat][1] != w0:', '            if False:', "hookc: cross-platform mismatch accepted"),
    (HC, 'return [] if a == b and type(a) is type(b) else', 'return [] if a == b else', "hookc: diff ignores bool/int"),
    (HC, '        if sha512half(ref) != meta["hookhash"]:', '        if False:', "hookc: foreign reference wasm accepted"),
    (HC, '            if sha512half(w2) != meta["hookhash"]:', '            if False:', "hookc: HookHash not compared"),
    (HC, '    if diff or dumps(regen) != meta["text"]:', '    if diff:', "hookc: metadata formatting drift accepted"),
    (HC, 'REL_RE = re.compile(r"^(?:(?!\\.\\.?(?:/|$))[A-Za-z0-9_.-]+(?:/(?!\\.\\.?(?:/|$))[A-Za-z0-9_.-]+)*)?$")', 'REL_RE = re.compile(r"^[A-Za-z0-9_./-]*$")', "hookc: loose relative path"),
    (V, '    if not defs or any(d != defs[0] for d in defs[1:]):', '    if False:', "verify: definition fields from disagreeing operators"),
    (V, 'out.append(dict(row, match=str(mv).upper() == str(dv).upper()))', 'out.append(dict(row, match=True))', "verify: definition fields always match"),
    (CLI, '        if recipe and recipe != want:', '        if False:', "cli: --recipe overrides hookc metadata"),
    (CLI, '        if params and params != meta["params"]:', '        if False:', "cli: --param overrides hookc metadata"),
    (HC, '    if not isinstance(on, dict) or on.get("form") not in ("omitted", "all", "list"):', '    if not isinstance(on, dict):', "hookc: human.on form unchecked"),
    (HC, '    if on["form"] == "list" and on.get("HookOn") is None:', '    if False:', "hookc: human list form without list"),
    (HC, '"on": "all" if on["form"] == "all" else on.get("HookOn"),', '"on": on.get("HookOn"),', "hookc: human on=all lost"),
    # ---- RT round 1 (2026-09-28 hostile red-team): one mutant per new fail-closed check ----
    # FP1/FP2/FP4/FN1/O4: rebuild only from the git export of the sidecar's commit; regenerate everything
    (HC, '        if head_tree != vcs["tree"]:', '        if False:', "rt FP1: --src HEAD tree not checked"),
    (HC, '        if info["vcs"]["commit"] != vcs["commit"] or info["vcs"]["tree"] != vcs["tree"]:', '        if False:', "rt FP1: exported commit/tree not compared"),
    (HC, '    if bool(src) == bool(git):\n        raise HookcError("give exactly one', '    if False:\n        raise HookcError("give exactly one', "rt FP1: both/neither sources accepted"),
    (HC, '        if loc is None:\n            raise HookcError("--src %s', '        if False:\n            raise HookcError("--src %s', "rt O4: --src not a git work tree accepted"),
    (HC, '        repo, rev, path = worktree_location(src)[0][0], vcs["commit"], vcs["path"]', '        return src, None, None', "rt FP4: work tree built instead of its commit"),
    (HC, '    return (params.get(ep) or None) if ep else None', '    return None', "rt FP2: compiled entry not recorded"),
    (HC, '    if entry != entry_of(tc, params):', '    if False:', "rt FP2: source.entry vs params unchecked"),
    (HC, '        if full != params:', '        if False:', "rt FP2/FP6: incomplete params accepted"),
    (HC, '            raise HookcError("builder.params %s are not valid for recipe %s: %s"', '            raise buildmod.BuildError("builder.params %s are not valid for recipe %s: %s"', "rt: invalid params escape as BuildError"),
    (HC, '    sb = source_block(None, info, entry_of(tc, params))', '    sb = dict(meta["source"])', "rt FP1: source block copied from the sidecar"),
    (HC, '    if manifest["source"]["tree_sha256"] != compiled_tree(info):', '    if False:', "rt F7: regenerate ignores container tree"),
    (HC, '        if tree_sha256 is not None and m["source"]["tree_sha256"] != tree_sha256:', '        if False:', "rt F7: double build ignores container tree"),
    (HC, '    if m1["image"]["image_id"] != m2["image"]["image_id"]:', '    if False:', "rt O5: double build on two images"),
    # FP6: preset label
    (HC, '    if preset is not None and not preset_matches(tc, preset, params):', '    if False:', "rt FP6: preset label unchecked"),
    (HC, '        if {k: v for k, v in base.items() if k != ep} != {k: v for k, v in params.items() if k != ep}:', '        if False:', "rt FP6: preset resolution not compared"),
    (HC, '        except buildmod.BuildError:\n            return False', '        except buildmod.BuildError:\n            return True', "rt FP6: unknown preset matches"),
    (HC, '    return preset if preset is not None and preset_matches(tc_name, preset, params) else None', '    return preset', "rt FP6: overridden params keep the label"),
    # FP5/C1/C2: export safety
    (HC, '        name = raw.decode("utf-8")', '        name = raw.decode("utf-8", "replace")', "rt C2: non-UTF-8 name decoded lossily"),
    (HC, '        if c in ("", ".", ".."):', '        if c in ("..",):', "rt C1: absolute / . components accepted"),
    (HC, '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', '        if False:', "rt C1: backslash/control chars accepted"),
    (HC, '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', '        if any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', "rt2 N2: leading '-' name accepted"),
    (HC, '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or not ch.isprintable() for ch in c):', "rt2 N2: whitespace (non-space) names accepted"),
    (HC, '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() for ch in c):', "rt2 N2: non-printable names accepted"),
    (HC, '        if c.startswith("-") or any(ch in UNSAFE_NAME_CHARS or ch.isspace() or not ch.isprintable() for ch in c):', '        if c.startswith("-") or any(ch.isspace() or not ch.isprintable() for ch in c):', "rt2 N2: metacharacter names accepted"),
    (HC, '        if _fold(c) == ".git" or c in TREE_IGNORE_DIRS:', '        if c in TREE_IGNORE_DIRS:', "rt C1: .GIT (case) accepted"),
    (HC, '        if _fold(c) == ".git" or c in TREE_IGNORE_DIRS:', '        if _fold(c) == ".git":', "rt F7: ignore dirs exported"),
    (HC, '            if other != p:', '            if False:', "rt FP5: collisions accepted"),
    (HC, '    return unicodedata.normalize("NFC", unicodedata.normalize("NFD", name).casefold())', '    return name.casefold()', "rt FP5: NFC/NFD collisions missed"),
    (HC, '    return unicodedata.normalize("NFC", unicodedata.normalize("NFD", name).casefold())', '    return unicodedata.normalize("NFC", name)', "rt FP5: case-fold collisions missed"),
    (HC, '        if hfn(b"%s %d\\0" % (kind.encode(), size) + data).hexdigest() != oid:', '        if False:', "rt2 N1: git objects not re-hashed (replaced/planted/corrupt accepted)"),
    (HC, '    if not os.path.normpath(out).startswith(root + os.sep):', '    if False:', "rt C1: lexical escape not refused"),
    (HC, '    if parent != root and not parent.startswith(root + os.sep):', '    if False:', "rt C1: symlinked parent escape not refused"),
    (HC, 'os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)', 'os.O_WRONLY | os.O_CREAT | os.O_TRUNC', "rt C1: export overwrites / follows links"),
    (HC, '    if written != listing:', '    if False:', "rt FP5: re-listing not compared"),
    (HC, '    if os.listdir(root):', '    if False:', "rt: non-empty export dir accepted"),
    # FP3 / L4: verify --metadata
    (V, '        if not rep["metadata_hookhash_matches"]:', '        if False:', "rt FP3: sidecar for another HookHash accepted"),
    (V, '        if sidecar is None:', '        if False:', "rt FP3: hookc sidecar not regenerated"),
    (V, '        except Exception as e:  # a sidecar that cannot be regenerated', '        except KeyError as e:  # a sidecar that cannot be regenerated', "rt FP3: regeneration error escapes"),
    (V, '            if not ok:\n                rep["verdict"] = "MISMATCH"', '            if False:\n                rep["verdict"] = "MISMATCH"', "rt FP3: regenerated sidecar difference ignored"),
    (V, '        if "fields" not in dc:', '        if False:', "rt FP3: disagreeing definitions not refused"),
    (V, '        bad = [r for r in dc["fields"] if r["enforced"] and r["match"] is False]', '        bad = [r for r in dc["fields"] if r["match"] is False]', "rt FP3: HookCanEmit enforced"),
    (V, '        if bad:', '        if False:', "rt FP3: definition DIFF only printed"),
    (V, 'ENFORCED_DEFINITION_FIELDS = ("Fee", "HookCallbackFee")', 'ENFORCED_DEFINITION_FIELDS = ("Fee", "HookCallbackFee", "HookOn")', "rt2 N4: first installer's HookOn enforced"),
    (V, 'DEFINITION_FIELDS = ("Fee", "HookCallbackFee", "HookOn", "HookCanEmit")', 'DEFINITION_FIELDS = ("Fee", "HookCallbackFee", "HookOn", "HookCanEmit", "ReferenceCount")', "rt L4: ReferenceCount compared"),
    (V, '    if i1 != i2:', '    if False:', "rt O5: rebuilds on different images"),
    # L1/O3: one validated ledger
    (F, '    if not HEX64.match(str(le.get("ledger_hash", ""))):', '    if False:', "rt L1: read without ledger hash"),
    (F, '    if type(le.get("ledger_index")) is not int or (ledger_index != "validated" and le["ledger_index"] != ledger_index):', '    if False:', "rt L1: re-read at another ledger accepted"),
    (F, '    li = min(r["ledger_index"] for r in out["reads"])', '    li = max(r["ledger_index"] for r in out["reads"])', "rt L1: common ledger = newest"),
    (F, '        if r["ledger_index"] != li:', '        if False:', "rt L1: newer operator not re-read"),
    (F, '    if len(hashes) != 1 or any(r["ledger_index"] != li for r in out["reads"]):', '    if False:', "rt L1: ledger hash disagreement accepted"),
    (F, '    if reread_errors:', '    if False:', "rt L1: re-read failure ignored"),
    # L2/O5: cache, image, version
    (BD, '    h.update(BUILD_ABI.encode() + b"\\0")', '    pass', "rt L2: hook-repro version not in recipe digest"),
    (BD, '        if sha256_file(dst) == a["sha256"]:\n            return dst', '        if True:\n            return dst', "rt L2: cached artifact not re-hashed"),
    (BD, '    except OSError as e:  # URLError, HTTPError, timeouts', '    except KeyError as e:  # URLError, HTTPError, timeouts', "rt L2: download error escapes"),
    (BD, '        if not isinstance(rec, dict) or rec.get("image_id") != have or rec.get("recipe_digest") != digest:', '        if not isinstance(rec, dict):', "rt O5: tag rebound to another image accepted"),
    (BD, '        if not isinstance(rec, dict) or rec.get("image_id") != have or rec.get("recipe_digest") != digest:', '        if False:', "rt O5: unrecorded tag accepted"),
    (BD, '    if r.returncode != 0 or not r.stdout.strip():\n        raise BuildError("docker image inspect', '    if False:\n        raise BuildError("docker image inspect', "rt O5: failed inspect after build accepted"),
    (BD, '        json.dump({"tag": tag, "image_id": image_id, "recipe_digest": digest}, f)', '        json.dump({}, f)', "rt O5: built image not recorded"),
    (BD, '    if os.path.lexists(ctx):\n        shutil.rmtree(ctx)', '    if False:\n        shutil.rmtree(ctx)', "rt L2: stale build context reused"),
    (BD, '    if os.path.lexists(root):\n        shutil.rmtree(root)\n    os.makedirs(os.path.join(root, "vendor"))', '    if os.path.lexists(root):\n        pass\n    os.makedirs(os.path.join(root, "vendor"), exist_ok=True)', "rt L2: vendor tree trusted"),
    (BD, '                h.update(b"F" + rel + b"\\0" + (b"x" if st.st_mode & 0o111 else b"-")\n                         + sha256_file(full).encode() + b"\\n")', '                pass', "rt L2: content digest ignores files"),
    (BD, '                h.update(b"L" + rel + b"\\0" + os.readlink(full).encode("utf-8", "surrogateescape") + b"\\n")', '                pass', "rt L2: content digest ignores symlinks"),
    (BD, '(b"x" if st.st_mode & 0o111 else b"-")', 'b"-"', "rt L2: content digest ignores exec bit"),
    # F7: staging
    (BD, '            if d in TREE_IGNORE_DIRS:\n                dirnames.remove(d)\n            elif os.path.islink', '            if False:\n                dirnames.remove(d)\n            elif os.path.islink', "rt F7: ignored dirs staged into the container"),
    (BD, '            elif os.path.islink(os.path.join(dirpath, d)):\n                raise BuildError', '            elif False:\n                raise BuildError', "rt F7: symlinked dir silently skipped"),
    (BD, '            if not stat.S_ISREG(st.st_mode):', '            if False:', "rt F7: symlinked file followed"),
    (BD, '    if th2 != th:', '    if False:', "rt F7: source swapped during build"),
    (BD, '        wasm = run_container(recipe, image, staged, private, p, vendor_dir=vendor_dir)', '        wasm = run_container(recipe, image, src_dir, private, p, vendor_dir=vendor_dir)', "rt F7: container gets the unstaged dir"),
    (HC, '    except OSError as e:\n        raise HookcError("cannot read metadata', '    except KeyError as e:\n        raise HookcError("cannot read metadata', "rt: missing metadata file is a traceback"),
    # ---- RT round 2 ----
    (BD, '        if not done:\n            kill_container(name)', '        if False:\n            kill_container(name)', "rt2 N7: timed-out container left running"),
    (BD, '    except subprocess.TimeoutExpired:\n        raise BuildError("container %s exceeded', '    except KeyError:\n        raise BuildError("container %s exceeded', "rt2 N7: container timeout is a traceback"),
    (CLI, '    except subprocess.TimeoutExpired as e:  # any docker/git step', '    except KeyError as e:  # any docker/git step', "rt2 N7: CLI timeout is a traceback"),
    (BD, '    r = run_named(cmd, name, timeout)', '    r = _run(cmd, timeout=timeout)', "rt2 N7: build container not run by name"),
    (HC, '        except buildmod.BuildError as e:\n            return None, "WCE tool did not finish', '        except KeyError as e:\n            return None, "WCE tool did not finish', "rt2 N7: WCE timeout escapes"),
    (V, '             for r in rows if r["enforced"] and r["match"] is True]', '             for r in rows if r["enforced"]]', "rt2 N4: reason names uncompared rows"),
    (V, '    absent = [r["definition"] for r in rows if r["enforced"] and r["match"] is None]', '    absent = []', "rt2 N4: uncompared enforced rows not stated"),
    (V, '            for r in rows if not r["enforced"]]', '            for r in rows if False]', "rt2 N4: informational rows not stated"),
    (HC, '           if not k.startswith("GIT_") and k not in ("HOME", "XDG_CONFIG_HOME", "EMAIL")}', '           if k not in ("HOME", "XDG_CONFIG_HOME", "EMAIL")}', "rt2 N1: caller GIT_* env reaches git"),
    (HC, '    env.update(HOME=home, XDG_CONFIG_HOME=home, GIT_CONFIG_NOSYSTEM="1"', '    env.update(GIT_CONFIG_NOSYSTEM="1"', "rt2 N1: global config/attributes apply"),
    (HC, 'GIT_ATTR_NOSYSTEM="1", GIT_NO_REPLACE_OBJECTS="1",', 'GIT_ATTR_NOSYSTEM="1",', "rt2 N1: GIT_NO_REPLACE_OBJECTS not set"),
    (HC, '    cmd = ["git", "--no-replace-objects", "-C", repo]', '    cmd = ["git", "-C", repo]', "rt2 N1: --no-replace-objects not passed"),
    (HC, '    for rel in ("objects/info/alternates", "objects/info/http-alternates", "info/grafts"):', '    for rel in ("objects/info/http-alternates", "info/grafts"):', "rt2 N1: alternates accepted"),
    (HC, '    for rel in ("objects/info/alternates", "objects/info/http-alternates", "info/grafts"):', '    for rel in ("objects/info/alternates", "objects/info/http-alternates"):', "rt2 N1: grafts accepted"),
    (HC, '        if len(oid) != hexlen:\n            raise HookcError("git object id %r', '        if False:\n            raise HookcError("git object id %r', "rt2 N1: object id length vs format unchecked"),
    (HC, '        if not name or b"/" in name or name in seen:', '        if not name or b"/" in name:', "rt2 N1: duplicate tree entries accepted"),
    (HC, '        if not name or b"/" in name or name in seen:', '        if not name or name in seen:', "rt2 N1: slash in tree entry name accepted"),
    (HC, '    if fmt not in HASHES:', '    if False:', "rt2 N1: unknown object format accepted"),
    (HC, '    if found:\n        raise HookcError("source %s: git attributes convert', '    if False:\n        raise HookcError("source %s: git attributes convert', "rt2 N3: converting gitattributes accepted"),
    (HC, '        if b".gitattributes" in ents:', '        if False:', "rt2 N3: ancestor .gitattributes not read"),
    (HC, 'if n == ".gitattributes" or n.endswith("/.gitattributes")]', 'if n == ".gitattributes"]', "rt2 N3: nested .gitattributes not read"),
    (HC, '    if os.path.isfile(local):', '    if False:', "rt2 N3: info/attributes not read"),
    (HC, 'CONVERTING_ATTRS = ("ident", "filter", "eol", "text", "crlf", "working-tree-encoding", "export-subst")', 'CONVERTING_ATTRS = ("filter", "eol", "text", "crlf", "working-tree-encoding", "export-subst")', "rt2 N3: ident accepted"),
    (HC, 'CONVERTING_ATTRS = ("ident", "filter", "eol", "text", "crlf", "working-tree-encoding", "export-subst")', 'CONVERTING_ATTRS = ("ident", "filter", "eol", "crlf", "working-tree-encoding", "export-subst")', "rt2 N3: text accepted"),
    (HC, '    check_attributes(repo, root_tree, path or "", ents, fmt, where)', '    pass', "rt2 N3: attributes never checked"),
    (HC, '                             m0["container_log"], sb, list(results))', '                             m0["container_log"], sb, sorted(tc["platforms"]))', "rt2 N6: sidecar claims every twin built"),
    (HC, '    if not built or len(set(built)) != len(built) or not set(built) <= set(pins):', '    if False:', "rt2 N6: unbuilt/duplicate twins claimable"),
    (HC, '    if (not isinstance(built, list) or not built or built != sorted(set(built))\n            or not set(built) <= set(toolchain(str(tc))["platforms"])):', '    if False:', "rt2 N6: malformed platforms_built accepted"),
    (HC, '    twins = [select_platform(meta, p) for p in ([platform] if platform else meta["platforms_built"])]', '    twins = [select_platform(meta, platform)]', "rt2 N6: platforms_built never re-checked"),
    (HC, '        for p2, _, _, w2 in got:', '        for p2, _, _, w2 in got[:1]:', "rt2 N6: only first twin compared"),
    (HC, '        built = None if platform else [p for p, _, _, _ in got]', '        built = None', "rt2 N6: re-checked twins not recorded"),
    (BD, '    if recipe.get("jail"):\n        lines = ["FROM %s" % recipe["base_image"], "# %s: pipeline', '    if False:\n        lines = ["FROM %s" % recipe["base_image"], "# %s: pipeline', "rt2 N5: jail recipes built without a jail"),
    (BD, '    j = "/jail" if recipe.get("jail") else ""', '    j = ""', "rt2 N5: C pipelines run with host /proc and /sys"),
    (BD, '        cmd += ["--tmpfs", "/sys:ro,size=4k"]', '        pass', "rt2 N5: container sysfs not masked"),
    (BD, '(["chroot", "/jail"] if j else [])', '[]', "rt2 N5: pipeline not chrooted"),
    (BD, 'JAIL_SETUP = ("mkdir /jail && for d in /*; do case \\"$d\\" in /proc|/sys|/dev|/jail|', 'JAIL_SETUP = ("mkdir /jail && for d in /*; do case \\"$d\\" in /jail|', "rt2 N5: /proc /sys /dev copied into the jail"),
    (BD, '    if type(r.get("jail", False)) is not bool:', '    if False:', "rt2 N5: jail flag unvalidated"),
    (BD, '        if refs:\n            raise BuildError("source names an absolute', '        if False:\n            raise BuildError("source names an absolute', "rt2 N5: host-path pre-scan ignored"),
    (BD, '    re.compile(rb"^[ \\t]*(?:#|%:)[ \\t]*(?:include|include_next|import|embed)\\b[ \\t]*[\\"<]([^\\">\\n]*)", re.M),', '    re.compile(rb"^#include \\"([^\\">\\n]*)", re.M),', "rt2 N5: only the plainest #include form scanned"),
    (BD, '    re.compile(rb"__has_(?:include|include_next|embed)\\s*\\(\\s*[\\"<]([^\\">\\n]*)"),', '    re.compile(rb"__has_include\\(\\"([^\\">\\n]*)"),', "rt2 N5: __has_include/__has_embed forms missed"),
    (BD, '    re.compile(rb"\\.incbin[\\s\\\\\\"]*([^\\s\\\\\\"]*)"),', '', "rt2 N5: asm .incbin not scanned"),
    (BD, '        text = _LINE_COMMENT.sub(b"", _BLOCK_COMMENT.sub(b" ", _SPLICE.sub(b"", text)))', '        pass', "rt2 N5: line splices/comments not normalised"),
    (BD, '        text = _LINE_COMMENT.sub(b"", _BLOCK_COMMENT.sub(b" ", _SPLICE.sub(b"", text)))', '        text = _SPLICE.sub(b"", text)', "rt2 N5: commented-out includes refused"),
    (HC, 'ENTRY_RE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]*\\.c$")', 'ENTRY_RE = re.compile(r"^[A-Za-z0-9_.-]+\\.c$")', "rt2 N2: entry may start with '-'"),
    # ---- RT round 3 ----
    (BD, '    if os.listdir(out_dir):\n        raise BuildError("container output dir', '    if False:\n        raise BuildError("container output dir', "rt3 R3-04: non-empty container out dir accepted"),
    (BD, '        wasm = run_container(recipe, image, staged, private, p, vendor_dir=vendor_dir)', '        wasm = run_container(recipe, image, staged, out_dir, p, vendor_dir=vendor_dir)', "rt3 R3-04: container mounts the user's --out"),
    (BD, '    if out_inside(out_dir, src_dir):', '    if False:', "rt3 R3-04: build out dir inside the source accepted"),
    (CLI, '    if r:\n        raise buildmod.BuildError("--out %s lies inside', '    if False:\n        raise buildmod.BuildError("--out %s lies inside', "rt3 R3-04: --out inside --src/--git accepted"),
    (BD, '            if o == rr or o.startswith(rr.rstrip(os.sep) + os.sep):', '            if o.startswith(rr):', "rt3 R3-04: sibling with a common prefix counted as inside"),
    (BD, '            if o == rr or o.startswith(rr.rstrip(os.sep) + os.sep):', '            if o.startswith(rr + os.sep):', "rt3 R3-04: --out equal to the source accepted"),
    (BD, '        if os.path.islink(src) or not os.path.isfile(src):', '        if False:', "rt3 R3-04: non-regular pipeline output published"),
    (BD, '        fd, tmp = tempfile.mkstemp(prefix=".hook-repro-", dir=out_dir)\n        with os.fdopen(fd, "wb") as fo, open(src, "rb") as fi:\n            shutil.copyfileobj(fi, fo)\n        os.chmod(tmp, 0o644)  # mkstemp creates 0600\n        os.replace(tmp, os.path.join(out_dir, name))', '        shutil.copyfile(src, os.path.join(out_dir, name))', "rt3 R3-04: publish follows a planted symlink"),
    (BD, '        publish_outputs(private, out_dir)', '        pass', "rt3 R3-04: outputs never published"),
    (BD, '    return op.startswith(b"/") or b".." in re.split(rb"[/\\\\\\\\]", op)', '    return op.startswith(b"/")', "rt3 R3-04/05: '..' operands accepted"),
    (BD, '    return op.startswith(b"/") or b".." in re.split(rb"[/\\\\\\\\]", op)', '    return op.startswith(b"/") or b".." in op.split(b"/")', "rt3 R3-05: backslash-separated '..' accepted"),
    (BD, '    op = op.strip()', '    pass', "rt3 R3-05: space before '..' hides it"),
    (BD, '            for m in rx.finditer(text):', '            for m in [x for x in [rx.search(text)] if x]:', "rt3 R3-05: only the first operand per form scanned"),
    (HC, '    funcs = sorted(name for name, kind, _ in mod["export_entries"] if kind == 0)', '    funcs = sorted(e.split(":")[0] for e in mod["exports"] if e.split(":")[1] == "0")', "rt3 R3-01: exports split on ':'"),
    (HC, '    funcs = sorted(name for name, kind, _ in mod["export_entries"] if kind == 0)', '    funcs = sorted(name for name, kind, _ in mod["export_entries"])', "rt3 R3-01: non-function export counted as a function"),
    (HC, '    if len(set(funcs)) != len(funcs):', '    if False:', "rt3 R3-01: duplicate function export accepted"),
    (W, '                mod["export_entries"].append((f, kind, idx))', '                mod["export_entries"].append((f.split(":")[0], kind, idx))', "rt3 R3-01: export name truncated at ':'"),
    (HC, '"commands": _log_commands(log), "wasm_opt": wasm_opt_ran(log)}', '"commands": _log_commands(log), "wasm_opt": any("wasm-opt" in c for c in _log_commands(log))}', "rt3 R3-02: wasm_opt from a command-line substring"),
    (HC, '        if line.startswith("--- "):\n            break\n        if line.startswith("HOOKC_WASM_OPT_RAN"):', '        if False:\n            break\n        if line.startswith("HOOKC_WASM_OPT_RAN"):', "rt3 R3-02: flag read from the commands/stages sections"),
    (HC, '    if len(vals) != 1 or vals[0] not in WASM_OPT_LINES:', '    if not vals:', "rt3 R3-02: repeated/malformed flag accepted"),
    (HC, '    if len(vals) != 1 or vals[0] not in WASM_OPT_LINES:', '    if len(vals) != 1:', "rt3 R3-02: malformed flag value accepted"),
    (HC, '    return vals[0] == WASM_OPT_LINES[1]', '    return True', "rt3 R3-02: wasm_opt always true"),
    (CLI, '        twins = [hookc.select_platform(meta, p) for p in ([plat] if plat else meta["platforms_built"])]', '        twins = [hookc.select_platform(meta, plat)]', "rt3 R3-03: verify rebuilds one twin"),
    (CLI, 'twins=twins, recheck_platforms_built=not plat, source_vcs=info["vcs"])', 'twins=twins, recheck_platforms_built=True, source_vcs=info["vcs"])', "rt3 R3-03: restricted verify claims re-checked"),
    (V, '    for plat, b1, _ in per_twin:', '    for plat, b1, _ in per_twin[:1]:', "rt3 R3-05: only the first twin compared to the chain"),
    (V, 'sidecar(bt, mt, [p for p, _ in twins] if rechecked else None)', 'sidecar(bt, mt, [twins[0][0]] if rechecked else None)', "rt3 R3-03: platforms_built regenerated from one twin"),
    (V, '    rechecked = bool(hookc_doc and recheck_platforms_built)', '    rechecked = hookc_doc', "rt3 R3-03: re-check claimed without a full rebuild"),
    (V, '        rep["platforms_built_rechecked"] = rechecked', '        rep["platforms_built_rechecked"] = True', "rt3 R3-03: report always says re-checked"),
    (V, '        on = " on %s" % plat if plat else ""', '        on = ""', "rt3 R3-03: failing twin not named"),
    (V, '            bdir = (os.path.join(out_dir, *([plat.replace("/", "-")] if plat else []), "build%d" % i)', '            bdir = (os.path.join(out_dir, "build%d" % i)', "rt3 R3-03: twins overwrite each other's outputs"),
    (HC, '        if prev is not None and key <= prev:', '        if False:', "rt3 R3-07: unsorted tree accepted"),
    (HC, '    return name + (b"/" if mode.lstrip("0") == "40000" else b"")', '    return name', "rt3 R3-07: tree order ignores the tree '/' suffix"),
    (HC, '        prev = key\n', '        pass\n', "rt3 R3-07: order never advances"),
    (HC, '        if c and (_fold(c) == ".git" or c in TREE_IGNORE_DIRS):', '        if c and c == ".git":', "rt3 R3-07: .GIT / ignore dirs in vcs.path accepted"),
    (HC, '    check_vcs_path(path)\n    fmt = git_repo_check(repo)', '    fmt = git_repo_check(repo)', "rt3 R3-07: export path components unchecked"),
    (HC, '    check_vcs_path(str(vcs.get("path", "")))', '    pass', "rt3 R3-07: sidecar vcs.path components unchecked"),
    (HC, '            or not all(isinstance(v, dict) for v in plats.values())):', '            or False):', "rt3 R3-08: non-object platforms entry accepted (traceback)"),
    (HC, '        except OSError as e:\n            rep["reason"] = "cannot read reference wasm', '        except KeyError as e:\n            rep["reason"] = "cannot read reference wasm', "rt3 R3-08: missing --wasm is a traceback"),
    (V, '                match=(dv is None) if expected is None else (dv is not None and str(dv) == expected))', '                match=True if expected is None else (dv is not None and str(dv) == expected))', "rt3 R3-09: HookCallbackFee present with WCE.cbak 0 accepted"),
    (V, '                match=(dv is None) if expected is None else (dv is not None and str(dv) == expected))', '                match=(dv is None) if expected is None else (dv is None or str(dv) == expected))', "rt3 R3-09: absent Fee/HookCallbackFee skipped"),
    (V, '    expected = None if (absent_when_zero and wce == 0) else str(wce)', '    expected = str(wce)', "rt3 R3-09: absent HookCallbackFee != WCE.cbak 0"),
    (V, '        return dict(row, expected=None, match=None)', '        return dict(row, expected=None, match=True)', "rt3 R3-09: null WCE counted as equal"),
    (V, '"HookCallbackFee", d.get("HookCallbackFee"), True)', '"HookCallbackFee", d.get("HookCallbackFee"), False)', "rt3 R3-09: HookCallbackFee treated like Fee"),
    (V, '        if hookc_doc:\n            rep["platforms_rebuilt"].append(plat)', '        if False:\n            rep["platforms_rebuilt"].append(plat)', "rt3 R3-03: rebuilt twins not reported"),
    (V, '        rep["platforms_rebuilt"] = []  # filled only', '        rep["platforms_rebuilt"] = [p for p, _ in twins][:0] + [p for p, _ in twins]  # filled only', "rt3 R3-03: planned twins reported as rebuilt"),
    # ---- RT round 4 ----
    (HC, '        if src:\n            check_worktree_matches(repo, vcs["path"], info["listing"])', '        if False:\n            check_worktree_matches(repo, vcs["path"], info["listing"])', "rt4 F2: --src work tree bytes never compared"),
    (HC, '        check_index_flags(repo, vcs["path"])\n    else:', '        pass\n    else:', "rt4 F2: skip-worktree/assume-unchanged index flags accepted"),
    (HC, '        if loc[1] not in ("", vcs["path"]):', '        if False:', "rt5 H-a: --src outside the sidecar's source dir accepted"),
    (HC, '        if tag != b"H":', '        if tag == b"S":', "rt4 F2: assume-unchanged (lowercase tag) accepted"),
    (HC, '    diff = sorted(set(have) ^ set(want)) + sorted(', '    diff = sorted(set(want) - set(have)) + sorted(', "rt4 F2: extra (untracked/ignored) work-tree files accepted"),
    (HC, 'sorted(n for n in set(have) & set(want) if have[n] != want[n])', '[]', "rt4 F2: work-tree names compared, bytes not"),
    (HC, '        if dirpath == root and not comps:', '        if True:', "rt4 F2: nested .git dirs skipped"),
    (HC, '            if os.path.islink(full):\n                raise HookcError("--src work tree has a symlink', '            if False:\n                raise HookcError("--src work tree has a symlink', "rt4 F2: symlinks in the work tree skipped"),
    (HC, '        if os.path.islink(root) or not os.path.isdir(root):', '        if not os.path.isdir(root):', "rt4 F2: symlinked --path component followed"),
    (HC, '        except WceUnavailable as e:  # a tool that did not run', '        except ZeroDivisionError as e:  # a tool that did not run', "rt4 F3: WCE tool failure escapes the reproduce report"),
    (HC, '    if not with_wce:\n        raise WceUnavailable(', '    if False:\n        raise WceUnavailable(', "rt4 F3: --no-wce recomputes nothing yet passes"),
    (HC, '    if wce is None:\n        raise WceUnavailable(', '    if False:\n        raise WceUnavailable(', "rt4 F3: WCE tool failure regenerates null (MISMATCH)"),
    (HC, '    if (doc.get("WCE") or {}).get("hook") is None:\n        return None, NO_WCE_REASON', '    if False:\n        return None, NO_WCE_REASON', "rt4 F3: --no-wce sidecar recomputed (MISMATCH with a working tool)"),
    (HC, '            if wce is None:\n                raise HookcError("WCE tool could not run', '            if False:\n                raise HookcError("WCE tool could not run', "rt4 F3b: build writes a null-WCE sidecar when the tool fails"),
    (HC, '    if (wce is None) != (wce_reason == NO_WCE_REASON) or (wce is not None and wce_reason is not None):', '    if False:', "rt4 F3b: make_metadata accepts any WCE reason"),
    (HC, '    nums = [v for v in (wce["hook"], wce["cbak"]) if type(v) is int and v >= 0]', '    nums = [v for v in (wce["hook"], wce["cbak"]) if isinstance(v, int)]', "rt4 F3b: bool / negative WCE accepted by parse"),
    (HC, '            or (wce["hook"] is None and wce["cbak"] is None and wb.get("reason") == NO_WCE_REASON)):', '            or (wce["hook"] is None and wce["cbak"] is None)):', "rt4 F3b: host-specific null-WCE reason accepted by parse"),
    (HC, '    if not ((len(nums) == 2 and wb.get("reason") is None)', '    if not ((len(nums) == 2)', "rt4 F3b: WCE numbers with a reason accepted by parse"),
    (B, '        elif rep.get("network") != network:', '        elif False:', "rt4 F4: binding network not checked against the report"),
    (B, '              "caveat": rep.get("caveat"),', '', "rt4 F4: report caveat dropped from the binding"),
    (B, '              "distinct_operators": rep.get("distinct_operators"),', '', "rt4 F4: distinct_operators dropped from the binding"),
    (B, '              "platforms_built_rechecked": rep.get("platforms_built_rechecked"),', '', "rt4 F4: platforms_built_rechecked dropped from the binding"),
    (B, '    if type(d) is not int or d < 2:', '    if d == 1:', "rt4 F4: missing/bool operator count not a caveat"),
    (B, '    if rep.get("platforms_built_rechecked") is False:', '    if False:', "rt4 F4: not-re-checked twins not a caveat"),
    (B, '        if network is None:\n            network = rep.get("network")', '        if False:\n            network = rep.get("network")', "rt4 F4: binding network not taken from the report"),
    (HC, '    git_config_check(repo)\n    fmt = _git(repo, "rev-parse", "--show-object-format")', '    fmt = _git(repo, "rev-parse", "--show-object-format")', "rt4 H1: --git repository config never checked"),
    (HC, '    git_config_check(src)  # the repository', '    pass  # the repository', "rt4 H1: work-tree repo config checked only after git status"),
    (HC, 'RISKY_CONFIG_RE = re.compile(r"^(?:filter\\.|include\\.|includeif\\.|core\\.worktree$)", re.I)', 'RISKY_CONFIG_RE = re.compile(r"^(?:filter\\.|core\\.worktree$)", re.I)', "rt4 H1: config includes accepted"),
    (HC, 'RISKY_CONFIG_RE = re.compile(r"^(?:filter\\.|include\\.|includeif\\.|core\\.worktree$)", re.I)', 'RISKY_CONFIG_RE = re.compile(r"^(?:include\\.|includeif\\.|core\\.worktree$)", re.I)', "rt4 H1: repo filter drivers accepted"),
    (HC, 'RISKY_CONFIG_RE = re.compile(r"^(?:filter\\.|include\\.|includeif\\.|core\\.worktree$)", re.I)', 'RISKY_CONFIG_RE = re.compile(r"^(?:filter\\.|include\\.|includeif\\.)", re.I)', "rt4 H1: core.worktree accepted"),
    (HC, '"core.attributesFile=/dev/null",', '', "rt4 H1: repo core.attributesFile honoured"),
    ("hook_repro/recipes/xhc-bin127/pipeline.sh", '$S/bin/clang -Wno-builtin-macro-redefined "$D1" "$D2" "$D3" $CLANG_FLAGS', '$S/bin/clang -Wno-builtin-macro-redefined "$D2" "$D3" $CLANG_FLAGS', "rt4 F1: xhc-bin127 __DATE__ left to clang 15 (wall clock)"),
    ("hook_repro/recipes/xhc-bin127/pipeline.sh", '$S/bin/clang -Wno-builtin-macro-redefined "$D1" "$D2" "$D3" $CLANG_FLAGS', '$S/bin/clang -Wno-builtin-macro-redefined $D1 $D2 $D3 $CLANG_FLAGS', "rt4 F1: date defines word-split"),
    ("hook_repro/recipes/xhc-bin127/pipeline.sh", "D1='-D__DATE__=\"Jan  1 1970\"'", "D1='-D__DATE__=\"Jan 1 1970\"'", "rt4 F1: __DATE__ not clang's SOURCE_DATE_EPOCH=0 form"),
    ("hook_repro/recipes/xhc-bin127/pipeline.sh", "D3='-D__TIMESTAMP__=\"Thu Jan  1 00:00:00 1970\"'", "D3='-D__TIMESTAMP__=\"Thu Jan 01 00:00:00 1970\"'", "rt4 F1: __TIMESTAMP__ not clang's SOURCE_DATE_EPOCH=0 form"),
    # ---- RT round 5 review: one mutant per fix ----
    (HC, '        if disagree:\n            raise HookcError("TWIN BUILD LOGS DISAGREE', '        if False:\n            raise HookcError("TWIN BUILD LOGS DISAGREE', "rt5 P1: build accepts twins whose logs disagree"),
    (HC, '    for p, l in rest:\n        f = log_fields(l)', '    for p, l in rest[:0]:\n        f = log_fields(l)', "rt5 P1: only the first twin's log read"),
    (HC, '        bad = [k for k in LOG_FIELDS if f[k] != f0[k]]', '        bad = [k for k in LOG_FIELDS[:1] if f[k] != f0[k]]', "rt5 P1: only builder.cc compared across twins"),
    (HC, '        for p2, _, m2, w2 in got:\n            try:\n                ok, why, rep["metadata_diff"] = sidecar_check(', '        for p2, _, m2, w2 in got[:1]:\n            try:\n                ok, why, rep["metadata_diff"] = sidecar_check(', "rt5 P1: reproduce regenerates the sidecar from the first twin only"),
    (V, '        for plat, bt, mt in per_twin:', '        for plat, bt, mt in per_twin[:1]:', "rt5 P1: verify regenerates the sidecar from the first twin only"),
    (V, '    if source_vcs is not None:\n        rep["source_vcs"] = source_vcs', '    if False:\n        rep["source_vcs"] = source_vcs', "rt5 P2: verify report written without source_vcs"),
    (BD, '    if os.path.lexists(root):\n        shutil.rmtree(root)\n    os.makedirs(os.path.join(root, "vendor"))', '    if os.path.isdir(os.path.join(root, "vendor")):\n        return os.path.join(root, "vendor"), info\n    os.makedirs(os.path.join(root, "vendor"))', "rt5 P3: cached vendor tree reused"),
    (BD, '    root = os.path.join(CACHE, "vendor", digest)', '    root = os.path.join(CACHE, "vendor", digest[:16])', "rt5 P3: vendor tree keyed by a 64-bit prefix"),
    (B, '    if uncompared or (isinstance(wce, dict) and wce.get("hook") is None):', '    if False:', "rt5 P5: --no-wce Fee/HookCallbackFee not-compared caveat dropped"),
    (B, '    uncompared = [str(r.get("definition")) for r in rows if r.get("enforced") and r.get("match") is None]', '    uncompared = []', "rt5 P5: uncompared enforced definition rows ignored"),
    (B, '    if uncompared or (isinstance(wce, dict) and wce.get("hook") is None):', '    if uncompared:', "rt5 P5: null sidecar WCE alone not a caveat"),
    # ---- hookc --select (entry selector for toolchains that compile every top-level .c) ----
    (HC, '    if toolchain(tc_name)["entry_param"]:\n        raise HookcError("toolchain %s has an entry parameter', '    if False:\n        raise HookcError("toolchain %s has an entry parameter', "select: accepted on a toolchain with an ENTRY param"),
    (HC, '    if select.startswith("/") or select.startswith("\\\\") or os.path.isabs(select):', '    if False:', "select: absolute path not refused as such"),
    (HC, '    if ".." in parts:', '    if False:', "select: '..' traversal not refused as such"),
    (HC, '    if len(parts) > 1:', '    if False:', "select: a path into a subdir accepted"),
    (HC, '    if not select.endswith(".c"):', '    if False:', "select: non-.c entry accepted"),
    (HC, '    if not ENTRY_RE.match(select):\n        raise HookcError("--select', '    if False:\n        raise HookcError("--select', "select: unsafe .c name accepted"),
    (HC, '    if stat.S_ISLNK(st.st_mode):', '    if False:', "select: symlinked entry not refused as such"),
    (HC, '    if not stat.S_ISREG(st.st_mode):\n        raise HookcError("--select', '    if False:\n        raise HookcError("--select', "select: non-regular entry accepted"),
    (HC, '    for n in withheld:\n        os.remove(os.path.join(dest, n))', '    for n in withheld[:1]:\n        os.remove(os.path.join(dest, n))', "select: one other .c left in the container"),
    (HC, 'if n.endswith(".c") and not os.path.isdir(os.path.join(root, n))),', 'if n.endswith(".c")),', "select: a directory named *.c withheld"),
    (HC, '    check_select(tc_name, select)\n', '', "select: name never checked in build"),
    (HC, '            want_tree = sel["tree_sha256"]', '            pass', "select: build checks the container against the full tree"),
    (HC, '        selection = info.get("selection", selection)', '        pass', "select: versioned source block drops the selection"),
    (HC, '    out["entry_selector"] = {', '    out["unrecorded"] = {', "select: selection not recorded as entry_selector"),
    (HC, '    return sel["tree_sha256"] if sel else info["tree_sha256"]', '    return info["tree_sha256"]', "select: rebuild checks the container against the full tree"),
    (HC, '        if "entry_selector" in meta["source"]:  # a --select sidecar', '        if False:  # a --select sidecar', "select: reproduce/verify rebuild every .c"),
    (HC, '        check_entry_selector(tc, entry, src["entry_selector"])', '        pass', "select: sidecar entry_selector unchecked"),
    (HC, '        check_select(tc, entry)  # also refuses', '        pass  # also refuses', "select: sidecar entry name/toolchain unchecked"),
    (HC, '    if not isinstance(sel, dict) or tuple(sel) != SELECTOR_KEYS:', '    if not isinstance(sel, dict):', "select: entry_selector keys unchecked"),
    (HC, '    if sel["by"] != BUILDER_NAME or sel["mode"] != SELECT_MODE:', '    if False:', "select: entry_selector by/mode unchecked"),
    (HC, '            or w != sorted(set(w), key=lambda n: n.encode("utf-8")) or entry in w):', '            or entry in w):', "select: unsorted withheld list accepted"),
    (HC, '    if not SHA_RE.match(str(sel["compiled_tree_sha256"])):', '    if False:', "select: compiled_tree_sha256 unchecked"),
    (HC, '    if type(n) is not int or n < 1:', '    if False:', "select: compiled_file_count unchecked"),
]
